### ISSUE TITLE
Have Python-Flask-Chat-App work in Python 3

### ISSUE THREAD

**Issue by Anish-M-code** [nandhubn/python-Flask-Chat-App#2]
I would like to run this Flask-Chat-App in Python 3 as Python 2 has reached end of support and most linux distributions are removing Python 2 packages. The only change required would be is to replace print  with print().

**Comment by nandhabn** [comment]
> I would like to run this Flask-Chat-App in Python 3 as Python 2 has reached end of support and most linux distributions are removing Python 2 packages. The only change required would be is to replace print with print().

changed...Thanks :)
